const {test, expext, expect} = require('@playwright/test')

test('Sauce hamburger button test', async({page}) => {
    await page.goto('https://www.saucedemo.com/')
    await page.locator('//*[@id="user-name"]').fill('standard_user')
    await page.locator('//*[@id="password"]').fill('secret_sauce')
    await page.click('//*[@id="login-button"]')
    await page.click('//*[@id="react-burger-menu-btn"]')
    await page.click('//*[@id="react-burger-cross-btn"]')
    await page.click('//*[@id="react-burger-menu-btn"]')
    await expect(page.locator('//*[@id="inventory_sidebar_link"]')).toBeVisible()
    await page.click('//*[@id="about_sidebar_link"]')
    await expect(page.locator('//*[@id="__next"]/div[2]/div[1]/div/div[1]/div[1]/div/div[4]/div[1]/a/button')).toBeVisible()
    await page.goBack();
    await page.click('//*[@id="react-burger-menu-btn"]')
    await page.click('//*[@id="logout_sidebar_link"]')
    await page.locator('//*[@id="user-name"]').fill('standard_user')
    await page.locator('//*[@id="password"]').fill('secret_sauce')
    await page.click('//*[@id="login-button"]')
    await page.click('//*[@id="react-burger-menu-btn"]')
    await expect(page.locator('//*[@id="reset_sidebar_link"]')).toBeVisible()
    await page.pause()
})
