export const selectors={
    "url" : "https://www.saucedemo.com/",
    "usernameInput" : '//*[@id="user-name"]',
    "passwordInput" : '//*[@id="password"]',
    "userName" : 'standard_user',
    "password" : 'secret_sauce',
    "loginButton" : '//*[@id="login-button"]',
    "headerText" : '//*[@id="header_container"]/div[1]/div[2]/div',
    "shoppingcartButton" : '//*[@id="shopping_cart_container"]',
    "hamburgerBtn" : '//*[@id="react-burger-menu-btn"]',
    "productsHeaderText" : '//*[@id="header_container"]/div[2]/span',
    "sortingProductButton" : '//*[@id="header_container"]/div[2]/div/span/select',
    "productDescription" : '//*[@id="inventory_container"]/div/div[1]/div[2]',
    "addToCartButton" : '//*[@id="add-to-cart-sauce-labs-backpack"]',
    "twitterButton" : '//*[@id="page_wrapper"]/footer/ul/li[1]/a',
    "facebookButton" : '//*[@id="page_wrapper"]/footer/ul/li[2]/a',
    "linkedinButton" : '//*[@id="page_wrapper"]/footer/ul/li[3]/a',
    "footerText" : '//div[@class="footer_copy"]',
    "logoutBtn" : '//*[@id="logout_sidebar_link"]',
    "lockedOutUsername" : 'locked_out_user',
    "lockedOutUserErrorMessage" : '//*[@id="login_button_container"]/div/form/div[3]/h3',
    "problemUserName" : 'problem_user',
    "itemImage" : '//*[@id="item_4_img_link"]',
    "glitchUserName" : 'performance_glitch_user',
    "wrongPassword" : 'test123',
    "wrongPasswordErrorMessage" : '//*[@id="login_button_container"]/div/form/div[3]/h3',
    "errorMessageTextForLockedUser" : 'Epic sadface: Sorry, this user has been locked out.',
    "errorMessageTextForWrongUserNameAndPassowrd" : 'Epic sadface: Username and password do not match any user in this service',
    "closeHamburgerButton" : '//*[@id="react-burger-cross-btn"]',
    "allItemsButton" : '//*[@id="inventory_sidebar_link"]',
    "aboutButton" : '//*[@id="about_sidebar_link"]',
    "textFromAnotherPage" : '//*[@id="__next"]/div[2]/div[1]/div/div[1]/div[1]/div/div[4]/div[1]/a/button',
    "resetAppBtn" : '//*[@id="reset_sidebar_link"]',
}